#!/usr/bin/env python3
"""
Save current SO-101 follower joint pose into project/config/runtime.json.

Typical use:
  1) Move the follower to a useful pose with teleoperation.
  2) Stop teleoperation while the arm remains there.
  3) Run this script to read the current joint positions and save them.

Examples:
  python -m lerobot.grad_project.tools.hybrid_save_pose \
    --robot.type=so101_follower \
    --robot.port=/dev/so101_follower \
    --robot.id=follower \
    --robot.disable_torque_on_disconnect=false \
    --runtime_config=project/config/runtime.json \
    --pose_name=observe \
    --save_gripper_as=open

  python -m lerobot.grad_project.tools.hybrid_save_pose \
    --robot.type=so101_follower \
    --robot.port=/dev/so101_follower \
    --robot.id=follower \
    --robot.disable_torque_on_disconnect=false \
    --runtime_config=project/config/runtime.json \
    --pose_name=slot1 \
    --mark_drop_slot=true

  # Save one grid calibration point. u/v comes from the OpenCV detector log.
  python -m lerobot.grad_project.tools.hybrid_save_pose \
    --robot.type=so101_follower \
    --robot.port=/dev/so101_follower \
    --robot.id=follower \
    --robot.disable_torque_on_disconnect=false \
    --runtime_config=project/config/runtime.json \
    --pregrasp_label=A1 \
    --u=312.4 \
    --v=210.8
"""


import json
import logging
from dataclasses import dataclass
from pathlib import Path
from pprint import pformat
from typing import Any

import draccus

from lerobot.grad_project.paths import detector_calib_path, runtime_config_path

from lerobot.grad_project.config_io import save_json_atomic

# Register robot/camera config subclasses for draccus CLI.
from lerobot.cameras.opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.robots import (  # noqa: F401
    RobotConfig,
    bi_so_follower,
    koch_follower,
    make_robot_from_config,
    omx_follower,
    so_follower,
)
from lerobot.utils.import_utils import register_third_party_plugins

try:
    from lerobot.grad_project.perception.opencv_block_detector import TopBlockDetector
except Exception:  # pragma: no cover - detector is optional for pose-only save
    TopBlockDetector = None  # type: ignore


@dataclass
class SavePoseConfig:
    robot: RobotConfig
    runtime_config: str = str(runtime_config_path(must_exist=False))

    # Save current pose under this name, e.g. observe, drop_center, slot1.
    pose_name: str = ""

    # If true, pose_name is appended to runtime["drop_slots"].
    mark_drop_slot: bool = False

    # Save current gripper value as runtime["gripper"][save_gripper_as].
    # Example: open or closed.
    save_gripper_as: str = ""

    # Save current pose as one pregrasp calibration point.
    # Need u/v pixel coordinate, unless auto_detect_pixel=true.
    pregrasp_label: str = ""
    u: float | None = None
    v: float | None = None

    # Optional: detect chosen block pixel from top frame automatically.
    # Only use this if the robot config includes top camera.
    auto_detect_pixel: bool = False
    detector_calib: str = str(detector_calib_path(must_exist=False))
    top_key: str = "top"


def _default_runtime() -> dict[str, Any]:
    return {
        "poses": {},
        "drop_slots": [],
        "pregrasp_points": [],
        "gripper": {},
        "metadata": {
            "note": "Generated by hybrid_save_pose.py. Pose keys must match robot.action_features.",
        },
    }


def load_runtime(path: str | Path) -> dict[str, Any]:
    path = Path(path)
    if not path.exists():
        return _default_runtime()
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    base = _default_runtime()
    base.update(data)
    base.setdefault("poses", {})
    base.setdefault("drop_slots", [])
    base.setdefault("pregrasp_points", [])
    base.setdefault("gripper", {})
    return base


def save_runtime(path: str | Path, data: dict[str, Any]) -> None:
    backup = save_json_atomic(path, data)
    if backup is not None:
        print(f"[BACKUP] previous runtime saved to {backup}")


def current_pose_from_robot(robot: Any) -> dict[str, float]:
    obs = robot.get_observation()
    pose: dict[str, float] = {}
    for key in robot.action_features:
        if key in obs:
            pose[key] = float(obs[key])
    if not pose:
        raise RuntimeError(
            "Could not read any joint position from robot.get_observation(). "
            f"action_features={list(robot.action_features)} obs_keys={list(obs)}"
        )
    return pose


def detect_pixel_from_robot(robot: Any, detector_calib: str, top_key: str) -> tuple[float, float, dict[str, Any]]:
    if TopBlockDetector is None:
        raise RuntimeError("TopBlockDetector could not be imported.")
    obs = robot.get_observation()
    if top_key not in obs:
        raise KeyError(f"Top camera key '{top_key}' not found in observation. keys={list(obs)}")
    detector = TopBlockDetector.load(detector_calib, frame_color="rgb")
    result = detector.detect(obs[top_key])
    if result.chosen is None:
        raise RuntimeError("OpenCV detector did not find a chosen outside block.")
    return float(result.chosen.cx), float(result.chosen.cy), result.chosen.to_json()


def upsert_pregrasp_point(runtime: dict[str, Any], label: str, u: float, v: float, pose: dict[str, float]) -> None:
    points = runtime.setdefault("pregrasp_points", [])
    new_point = {"label": label, "u": float(u), "v": float(v), "pose": pose}
    for i, p in enumerate(points):
        if p.get("label") == label:
            points[i] = new_point
            return
    points.append(new_point)


@draccus.wrap()
def main(cfg: SavePoseConfig) -> None:
    logging.basicConfig(level=logging.INFO)
    logging.info("Config:\n%s", pformat(cfg))

    runtime_path = runtime_config_path(cfg.runtime_config, must_exist=False)
    detector_path = detector_calib_path(
        cfg.detector_calib,
        must_exist=cfg.auto_detect_pixel,
    )
    print(f"[CONFIG] runtime_config={runtime_path}")
    if cfg.auto_detect_pixel:
        print(f"[CONFIG] detector_calib={detector_path}")

    robot = make_robot_from_config(cfg.robot)
    robot.connect()
    try:
        runtime = load_runtime(runtime_path)
        pose = current_pose_from_robot(robot)

        changed = False

        if cfg.pose_name:
            runtime.setdefault("poses", {})[cfg.pose_name] = pose
            print(f"[OK] saved pose '{cfg.pose_name}'")
            changed = True

            if cfg.mark_drop_slot and cfg.pose_name not in runtime.setdefault("drop_slots", []):
                runtime["drop_slots"].append(cfg.pose_name)
                print(f"[OK] added '{cfg.pose_name}' to drop_slots")

        if cfg.save_gripper_as:
            gripper_key = "gripper.pos"
            if gripper_key not in pose:
                raise KeyError(f"'{gripper_key}' not found in current pose: {pose}")
            runtime.setdefault("gripper", {})[cfg.save_gripper_as] = float(pose[gripper_key])
            print(f"[OK] saved gripper '{cfg.save_gripper_as}' = {pose[gripper_key]:.3f}")
            changed = True

        if cfg.pregrasp_label:
            u, v = cfg.u, cfg.v
            det_info = None
            if cfg.auto_detect_pixel:
                u, v, det_info = detect_pixel_from_robot(robot, str(detector_path), cfg.top_key)
                print(f"[OK] auto detected pixel for {cfg.pregrasp_label}: u={u:.1f}, v={v:.1f}, det={det_info}")
            if u is None or v is None:
                raise ValueError("pregrasp_label needs --u and --v, or set --auto_detect_pixel=true")
            upsert_pregrasp_point(runtime, cfg.pregrasp_label, float(u), float(v), pose)
            print(f"[OK] saved pregrasp point '{cfg.pregrasp_label}' at pixel ({u:.1f}, {v:.1f})")
            changed = True

        if not changed:
            print("Nothing saved. Use --pose_name=..., --save_gripper_as=..., or --pregrasp_label=...")
            print("Current pose:")
            print(json.dumps(pose, ensure_ascii=False, indent=2))
            return

        save_runtime(runtime_path, runtime)
        print(f"[OK] wrote {runtime_path}")
        print(json.dumps(runtime, ensure_ascii=False, indent=2))

    finally:
        robot.disconnect()


if __name__ == "__main__":
    register_third_party_plugins()
    main()
